// Skills a person can offer — shown under "REWARD" on the People page and
// landing gazette. Multi-select in the Edit Profile form.
export const SKILLS = [
  "Painting",
  "Drawing",
  "Illustration",
  "Printmaking",
  "Sculpture",
  "Photography",
  "Videography",
  "Film Editing",
  "Color Grading",
  "Sound Design",
  "Mixing",
  "Music Production",
  "Songwriting",
  "Instrumental Performance",
  "Vocals",
  "Acting",
  "Directing",
  "Choreography",
  "Creative Writing",
  "Poetry",
  "Screenwriting",
  "Graphic Design",
  "UX Design",
  "Animation",
  "3D Modeling",
];
